### ISSUE TITLE
Ruby code is not getting the right colors.

### ISSUE THREAD

**Issue by cristianstu** [atom/language-ruby#252]
### Description

Ruby code is not getting the right colors.
Light theme seems to be ok.

### Steps to Reproduce

1. Upload to atom >= 1.32.0
2. Open any ruby file.

**Expected behavior:** Show the file like this

![image](https://user-images.githubusercontent.com/3144786/48094297-8c79e700-e1f0-11e8-9e09-46d6166e31a0.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/3144786/48094279-78ce8080-e1f0-11e8-93e0-2388852173a4.png)

**Reproduces how often:** Always

### Versions

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15+
git 2.19.1

### Additional Information

Seems like syntax--ruby class is missing on hierarchy. Switching to Ruby On Rails syntax fix the problem.

**Comment by Ben3eeE** [comment]
@simurai The missing `syntax--source syntax--ruby` should be fixed in Atom 1.32.2 and later via https://github.com/atom/language-ruby/commit/0208636827aef4f420c5d94ec4ef43bbaf8a264e.

**Comment by Ben3eeE** [comment]
Running a build from latest master looks like this with solarized-dark-syntax:
![image](https://user-images.githubusercontent.com/1058982/48467048-12e18a80-e7e8-11e8-8873-fb6394b0551a.png)

**Comment by simurai** [comment]
> should be fixed in Atom 1.32.2 and later

Nice! 🙌 

> Which version of the package is nightly12 using?

Ouch.. sorry, this is embarrassing. :sweat_smile: I had some other example code above 

```
class Article < ApplicationRecord
  belongs_to :category, optional: true
end
```

... which then probably messed up the highlighting. OK, works also in nightly12. 👍 Closing! And thanks for the checking. @Ben3eeE

**Comment by josephchoe** [comment]
If some of the colors still don't look right on the solarized dark theme, but the `syntax--ruby` classes are being populated on the hierarchy, does that mean this issue needs to go back to the `atom/solarized-dark-syntax` repository?

For example:

<img width="1206" alt="screen shot 2018-11-19 at 2 18 35 am" src="https://user-images.githubusercontent.com/15367014/48700700-7df0df80-eba1-11e8-8999-ba9c6b7cb6cc.png">

**Comment by simurai** [comment]
> @josephchoe does that mean this issue needs to go back to the `atom/solarized-dark-syntax` repository?

Yes, it seems that `require` gets intentionally overridden here: https://github.com/atom/solarized-dark-syntax/blob/74bc0df24ca7493d9d8bcfcaedccb5cc05c2c2f9/styles/syntax/ruby.less#L123-L125

Removing it, makes `require` blue. Not sure if that is prefered?

![image](https://user-images.githubusercontent.com/378023/48750810-62cac080-ecc4-11e8-9483-4c67c1fd8986.png)

**Comment by josephchoe** [comment]
I think it's supposed to be like this? Though I might be remembering wrong.

<img width="476" alt="screen shot 2018-11-22 at 9 57 07 pm" src="https://user-images.githubusercontent.com/15367014/48929914-a890b000-eea1-11e8-80c4-5d18aedea10b.png">

**Comment by simurai** [comment]
> @josephchoe does that mean this issue needs to go back to the `atom/solarized-dark-syntax` repository?
> @josephchoe I think it's supposed to be like this?

Sorry, you're right. The scopes seem to be different:

Before (TextMate) | After (Tree-sitter)
--- | ---
![textmate](https://user-images.githubusercontent.com/378023/49355154-9ddbe380-f709-11e8-90da-08027d2d8242.png) | ![tree-sitter](https://user-images.githubusercontent.com/378023/49355155-9ddbe380-f709-11e8-860a-d1a6a0327299.png)
![solarized-textmate](https://user-images.githubusercontent.com/378023/49355157-9e747a00-f709-11e8-8a2c-1eec37f0834e.png) | ![solarized-tree-sitter](https://user-images.githubusercontent.com/378023/49355156-9ddbe380-f709-11e8-8339-e965362ab931.png)

But it's different for all themes, not just Solarized. Not sure if it's possible to change the Tree-sitter grammar so that it matches TextMate's?

I'll re-open it here. It might be a duplicate of any of these https://github.com/atom/language-ruby/labels/tree-sitter.

**Comment by maxbrunsfeld** [comment]
> I think it's supposed to be like this?

IMO the new behavior makes more sense. `require` isn't a keyword; it's a built-in function, so I think `support.function` is the right scope. If solarized doesn't highlight `support.function`, then I think a lot of languages are going to look wrong, not just Ruby, because that's the scope used for "special" functions in many languages.

**Comment by gsmetal** [comment]
Hello, any updates here? There are a lot of problems with highlighting on tree sitter. For example: 
![image](https://user-images.githubusercontent.com/699661/56027157-328cc880-5d1e-11e9-882f-143721df736f.png)

1. Aren't `include` and `extend` built-in functions same as `require`?
1. Function's argument with assignment is not highlighted as argument.
1. `super` is not highlighted at all.
1. Last `var` is highlighted as function, but it's definitely not a function.
1.  ...

**Comment by Ben3eeE** [comment]
> 1. Aren't include and extend built-in functions same as require?

I don't know Ruby so I can't answer this question but if they are you can add them here and change it from `exact` to `match` so it's a regex. There are quite a few built in functions that are not scoped.

https://github.com/atom/language-ruby/blob/0592946a72481f307860927e8c5a37c705388985/grammars/tree-sitter-ruby.cson#L155

> 2. Function's argument with assignment is not highlighted as argument.

This should be easy to fix by just adding:
`'optional_parameter > identifier': 'variable.parameter.function'`

Here:
https://github.com/atom/language-ruby/blob/0592946a72481f307860927e8c5a37c705388985/grammars/tree-sitter-ruby.cson#L160

> 3. super is not highlighted at all.

Same thing. Add a line for it `'super': 'the-scope.i-want'` or `'"super"': 'the-scope.i-want'`. The one that works is the correct one.

> 4. Last var is highlighted as function, but it's definitely not a function.

Not as easy to fix as the other things.

> 5. ...

...

PRs are welcome to add these things.

**Comment by chbk** [comment]
I believe this can be closed when #291 is merged.
